export const UPDATE_PERSONAL_INFO = 'UPDATE_PERSONAL_INFO';
export const UPDATE_RELATIVE_INFO = 'UPDATE_RELATIVE_INFO';
export const FINISH_ONBOARDING = 'FINISH_ONBOARDING';
export const RESPAWN_ONBOARDING = 'RESPAWN_ONBOARDING';
