export const FINISH_ONBOARDING = 'FINISH_ONBOARDING';
export const UPDATE_PERSONAL_INFO = 'UPDATE_PERSONAL_INFO';
export const UPDATE_RELATIVE_INFO = 'UPDATE_RELATIVE_INFO';
export const SAVE_DAILY_REPORT = 'SAVE_DAILY_REPORT';
