export const FINISH_ONBOARDING = 'FINISH_ONBOARDING';
export const RESPAWN_ONBOARDING = 'RESPAWN_ONBOARDING';
export const UPDATE_PERSONAL_INFO = 'UPDATE_PERSONAL_INFO';
export const UPDATE_RELATIVE_INFO = 'UPDATE_RELATIVE_INFO';
export const UPDATE_WEIGHT = 'UPDATE_WEIGHT';
export const ADD_LIFESPAN_MODIFIER = 'ADD_LIFESPAN_MODIFIER';
export const REMOVE_ALL_USER_MODIFIERS = 'REMOVE_ALL_USER_MODIFIERS';
export const REMOVE_LAST_MODIFIER = 'REMOVE_LAST_MODIFIER';
